name: pharma_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.0.0
  latlong2: ^0.9.1
  http: ^1.2.0
  firebase_core: ^3.11.0
  supabase_flutter: ^2.8.3

  # PACKAGES CARTOGRAPHIE (Compatibles avec flutter_map v8)
  flutter_map: ^8.2.2
  vector_map_tiles: ^9.0.0-beta.8             
  vector_tile_renderer: ^6.0.0         
  flutter_map_location_marker: ^10.2.0
  flutter_map_marker_cluster: ^8.2.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
