// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3RhElIMHhGuzB61pLGeRHwYDfuWUymOc',
    appId: '1:637046836941:web:2dd76e7df61c2a04e06384',
    messagingSenderId: '637046836941',
    projectId: 'pharma-app-be26a',
    authDomain: 'pharma-app-be26a.firebaseapp.com',
    storageBucket: 'pharma-app-be26a.firebasestorage.app',
    measurementId: 'G-SDVG2G8CZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwHU4uuSSHgX5NG2WTDe8sDE68b-zvmM',
    appId: '1:637046836941:android:a21e995c53112d63e06384',
    messagingSenderId: '637046836941',
    projectId: 'pharma-app-be26a',
    storageBucket: 'pharma-app-be26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxpRCq-tXf9ofCkgsHNy4QjJWsti4-PE',
    appId: '1:637046836941:ios:5838df6daeaa41b6e06384',
    messagingSenderId: '637046836941',
    projectId: 'pharma-app-be26a',
    storageBucket: 'pharma-app-be26a.firebasestorage.app',
    iosBundleId: 'com.example.pharmaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxpRCq-tXf9ofCkgsHNy4QjJWsti4-PE',
    appId: '1:637046836941:ios:5838df6daeaa41b6e06384',
    messagingSenderId: '637046836941',
    projectId: 'pharma-app-be26a',
    storageBucket: 'pharma-app-be26a.firebasestorage.app',
    iosBundleId: 'com.example.pharmaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3RhElIMHhGuzB61pLGeRHwYDfuWUymOc',
    appId: '1:637046836941:web:89629610f3ad3ccce06384',
    messagingSenderId: '637046836941',
    projectId: 'pharma-app-be26a',
    authDomain: 'pharma-app-be26a.firebaseapp.com',
    storageBucket: 'pharma-app-be26a.firebasestorage.app',
    measurementId: 'G-CSF5Q1LPFG',
  );
}
